name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    outputs:
      run_job: ${{ steps.check.outputs.run_job }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: check modified files
        id: check
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD

          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file == *.go ]]; then
              echo "run job"
              echo "::set-output name=run_job::true"
              break
            fi
          done < files.txt

  lint:
    name: Lint
    needs: check
    if: needs.check.outputs.run_job == 'true'
    runs-on: ubuntu-latest
    env:
      GO_VERSION: '1.16.7'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup go
        id: go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache go
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Golangci lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1
          skip-go-installation: true
          skip-pkg-cache: true
          skip-build-cache: true
          only-new-issues: true
          args: -v ./...
